# Generated by Django 4.0.3 on 2022-04-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture10_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='author',
            field=models.CharField(default='noone', max_length=255, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='posts',
            name='date',
            field=models.DateField(default='1900-01-01'),
        ),
        migrations.AddField(
            model_name='posts',
            name='desc',
            field=models.CharField(default=' ', max_length=100, verbose_name='туралы'),
        ),
        migrations.AddField(
            model_name='posts',
            name='place',
            field=models.CharField(default=' ', max_length=255, verbose_name='Шығарылған жері'),
        ),
    ]
