# Generated by Django 4.0.3 on 2022-04-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture10_app', '0002_posts_author_posts_date_posts_desc_posts_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='date',
            field=models.DateField(default='01-01-2020', verbose_name='DAY-MONTH-YEAT'),
        ),
    ]
