# Generated by Django 4.0.3 on 2022-04-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture10_app', '0006_alter_posts_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='date',
            field=models.DateField(default='01-01-2020', verbose_name='%d-%m-%Y'),
        ),
    ]
